# Generated by Django 3.2.16 on 2023-05-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'объект «Автор»', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'объект «Книга»', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'объект «Категория»', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'объект «Издатель»', 'verbose_name_plural': 'Издатели'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='series',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Имя автора'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть книгу.', verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть категорию.', verbose_name='Опубликовано'),
        ),
    ]
